version: '3.9'

x-backend: &app
  stdin_open: true
  tty: true

services:
  api:
    <<: *app
    build: .
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - bundle-cache:/usr/local/bundle
    ports:
      - 3000:3000

volumes:
  bundle-cache: null

